" Enable terminal colors
set t_Co=256

syntax on

set background=dark
" or, for the light background mode:
" set background=light

colorscheme vividchalk

set cursorline

" Search behaviour
set hlsearch " Highlight search results


" show line number
set number

" Indentation and tabs
" use SOFT tabs (not pure tab but spaces)
set expandtab " remove for pure tabs
set shiftwidth=3
set softtabstop=3 " use tabstop for pure tab
filetype indent on


" Netrw file tree
let g:netrw_liststyle=3


" Pathogen plugin management
call pathogen#infect()
call pathogen#helptags()

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
